
const UPDATE_USER = 'UPDATE_USER';
const SET_QUESTIONS = 'SET_QUESTIONS';
const SET_USERS = 'SET_USERS';
const UPDATE_FOCUSED_USER = 'UPDATE_FOCUSED_USER';

export { UPDATE_USER, SET_QUESTIONS, SET_USERS, UPDATE_FOCUSED_USER };
