
const UPDATE_USER = 'UPDATE_USER';
const SET_QUESTIONS = 'SET_QUESTIONS';
const SET_USERS = 'SET_USERS';
const UPDATE_FOCUSED_USER = 'UPDATE_FOCUSED_USER';
const SET_FOCUSED_USER_QUESTIONS = 'SET_FOCUSED_USER_QUESTIONS';

export {
  UPDATE_USER,
  SET_QUESTIONS,
  SET_USERS,
  UPDATE_FOCUSED_USER,
  SET_FOCUSED_USER_QUESTIONS,
};
